/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const WorkspaceLazyRouteImport = createFileRoute('/workspace')()
const WelcomeLazyRouteImport = createFileRoute('/welcome')()
const ResetPasswordLazyRouteImport = createFileRoute('/reset-password')()
const RegisterLazyRouteImport = createFileRoute('/register')()
const LoginLazyRouteImport = createFileRoute('/login')()
const HistoryLazyRouteImport = createFileRoute('/history')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgot-password')()
const AutopostLazyRouteImport = createFileRoute('/autopost')()
const IndexLazyRouteImport = createFileRoute('/')()
const LoginGoogleCallbackLazyRouteImport = createFileRoute(
  '/login/google-callback',
)()

const WorkspaceLazyRoute = WorkspaceLazyRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/workspace.lazy').then((d) => d.Route))
const WelcomeLazyRoute = WelcomeLazyRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/welcome.lazy').then((d) => d.Route))
const ResetPasswordLazyRoute = ResetPasswordLazyRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const HistoryLazyRoute = HistoryLazyRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const AutopostLazyRoute = AutopostLazyRouteImport.update({
  id: '/autopost',
  path: '/autopost',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/autopost.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LoginGoogleCallbackLazyRoute = LoginGoogleCallbackLazyRouteImport.update({
  id: '/google-callback',
  path: '/google-callback',
  getParentRoute: () => LoginLazyRoute,
} as any).lazy(() =>
  import('./routes/login.google-callback.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/autopost': typeof AutopostLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/welcome': typeof WelcomeLazyRoute
  '/workspace': typeof WorkspaceLazyRoute
  '/login/google-callback': typeof LoginGoogleCallbackLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/autopost': typeof AutopostLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/welcome': typeof WelcomeLazyRoute
  '/workspace': typeof WorkspaceLazyRoute
  '/login/google-callback': typeof LoginGoogleCallbackLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/autopost': typeof AutopostLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/welcome': typeof WelcomeLazyRoute
  '/workspace': typeof WorkspaceLazyRoute
  '/login/google-callback': typeof LoginGoogleCallbackLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autopost'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/workspace'
    | '/login/google-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autopost'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/workspace'
    | '/login/google-callback'
  id:
    | '__root__'
    | '/'
    | '/autopost'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/workspace'
    | '/login/google-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AutopostLazyRoute: typeof AutopostLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
  LoginLazyRoute: typeof LoginLazyRouteWithChildren
  RegisterLazyRoute: typeof RegisterLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  WelcomeLazyRoute: typeof WelcomeLazyRoute
  WorkspaceLazyRoute: typeof WorkspaceLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopost': {
      id: '/autopost'
      path: '/autopost'
      fullPath: '/autopost'
      preLoaderRoute: typeof AutopostLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/google-callback': {
      id: '/login/google-callback'
      path: '/google-callback'
      fullPath: '/login/google-callback'
      preLoaderRoute: typeof LoginGoogleCallbackLazyRouteImport
      parentRoute: typeof LoginLazyRoute
    }
  }
}

interface LoginLazyRouteChildren {
  LoginGoogleCallbackLazyRoute: typeof LoginGoogleCallbackLazyRoute
}

const LoginLazyRouteChildren: LoginLazyRouteChildren = {
  LoginGoogleCallbackLazyRoute: LoginGoogleCallbackLazyRoute,
}

const LoginLazyRouteWithChildren = LoginLazyRoute._addFileChildren(
  LoginLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AutopostLazyRoute: AutopostLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  HistoryLazyRoute: HistoryLazyRoute,
  LoginLazyRoute: LoginLazyRouteWithChildren,
  RegisterLazyRoute: RegisterLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  WelcomeLazyRoute: WelcomeLazyRoute,
  WorkspaceLazyRoute: WorkspaceLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
