from __future__ import annotations

import os
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from api.routers import (
    auth_router,
    content_plan_router,
    conversation_router,
    health_router,
    history_router,
    project_router,
    user_router,
)
from shared.logging import setup_logging

setup_logging(is_production=False)

_default_cors_origins = (
    "http://localhost:5173,"
    "http://127.0.0.1:5173,"
    "http://localhost:3000,"
    "http://127.0.0.1:3000"
)
_cors_origins = [
    origin.strip()
    for origin in os.getenv("CORS__ALLOW_ORIGINS", _default_cors_origins).split(",")
    if origin.strip()
]
_cors_origin_regex = os.getenv(
    "CORS__ALLOW_ORIGIN_REGEX",
    (
        r"https?://("
        r"localhost|127\.0\.0\.1|0\.0\.0\.0|"
        r"192\.168\.\d{1,3}\.\d{1,3}|"
        r"10\.\d{1,3}\.\d{1,3}\.\d{1,3}|"
        r"172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}"
        r")(:\d+)?$"
    ),
)

_default_upload_dir = (Path(__file__).resolve().parent / "uploads").as_posix()
_upload_dir = Path(os.getenv("USER__UPLOAD_DIR", _default_upload_dir)).resolve()
_upload_dir.mkdir(parents=True, exist_ok=True)
(_upload_dir / "avatars").mkdir(parents=True, exist_ok=True)

app = FastAPI(
    title="Agent Content Planner",
    description=(
        "AI-powered content planning API. "
        "Provide a blog/article URL and receive ready-to-post content "
        "for LinkedIn and Facebook generated by a multi-agent CrewAI pipeline."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS (adjust origins in production) ──────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_origin_regex=_cors_origin_regex,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/uploads", StaticFiles(directory=str(_upload_dir)), name="uploads")

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(health_router, prefix="/api/v1")
app.include_router(content_plan_router, prefix="/api/v1")
app.include_router(user_router, prefix="/api/v1")
app.include_router(auth_router, prefix="/api/v1")
app.include_router(project_router, prefix="/api/v1")
app.include_router(conversation_router, prefix="/api/v1")
app.include_router(history_router, prefix="/api/v1")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
