from __future__ import annotations

import asyncio
import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from api.helpers.exception_handler import (
    to_http_detail_message,
    to_user_error_message,
    to_validation_error_message,
)
from api.routers import (
    auth_router,
    content_plan_router,
    conversation_router,
    health_router,
    history_router,
    project_router,
    user_router,
)
from shared.logging import get_logger, setup_logging
from shared.thread_pools import install_default_executors, shutdown_executors

setup_logging(is_production=False)
logger = get_logger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    loop = asyncio.get_running_loop()
    install_default_executors(loop)
    try:
        yield
    finally:
        shutdown_executors()


_default_cors_origins = (
    "http://localhost:5173,"
    "http://127.0.0.1:5173,"
    "http://localhost:3000,"
    "http://127.0.0.1:3000"
)
_cors_origins = [
    origin.strip()
    for origin in os.getenv("CORS__ALLOW_ORIGINS", _default_cors_origins).split(",")
    if origin.strip()
]
_cors_origin_regex = os.getenv(
    "CORS__ALLOW_ORIGIN_REGEX",
    (
        r"https?://("
        r"localhost|127\.0\.0\.1|0\.0\.0\.0|"
        r"192\.168\.\d{1,3}\.\d{1,3}|"
        r"10\.\d{1,3}\.\d{1,3}\.\d{1,3}|"
        r"172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}"
        r")(:\d+)?$"
    ),
)

_default_upload_dir = (Path(__file__).resolve().parent / "uploads").as_posix()
_upload_dir = Path(os.getenv("USER__UPLOAD_DIR", _default_upload_dir)).resolve()
_upload_dir.mkdir(parents=True, exist_ok=True)
(_upload_dir / "avatars").mkdir(parents=True, exist_ok=True)

app = FastAPI(
    title="Agent Content Planner",
    description=(
        "AI-powered content planning API. "
        "Provide a blog/article URL and receive ready-to-post content "
        "for LinkedIn and Facebook generated by a multi-agent CrewAI pipeline."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)


def _error_response(*, status_code: int, message: str) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content={"success": False, "data": None, "error": message},
    )


@app.exception_handler(RequestValidationError)
async def _handle_request_validation_error(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    logger.warning(
        "request_validation_failed",
        path=request.url.path,
        method=request.method,
        error_count=len(exc.errors()),
    )
    return _error_response(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        message=to_validation_error_message(exc.errors()),
    )


@app.exception_handler(HTTPException)
async def _handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    message = to_http_detail_message(detail=exc.detail, status_code=exc.status_code)
    return _error_response(status_code=exc.status_code, message=message)


@app.exception_handler(Exception)
async def _handle_unexpected_exception(
    request: Request, exc: Exception
) -> JSONResponse:
    if isinstance(exc, asyncio.CancelledError):
        raise exc
    logger.exception(
        "unhandled_exception",
        path=request.url.path,
        method=request.method,
        error=str(exc),
    )
    return _error_response(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        message=to_user_error_message(
            error=str(exc),
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            fallback="Something went wrong on our side. Please try again later.",
        ),
    )


# ── CORS (adjust origins in production) ──────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_origin_regex=_cors_origin_regex,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/uploads", StaticFiles(directory=str(_upload_dir)), name="uploads")

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(health_router, prefix="/api/v1")
app.include_router(content_plan_router, prefix="/api/v1")
app.include_router(user_router, prefix="/api/v1")
app.include_router(auth_router, prefix="/api/v1")
app.include_router(project_router, prefix="/api/v1")
app.include_router(conversation_router, prefix="/api/v1")
app.include_router(history_router, prefix="/api/v1")

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
